<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!--NewPage-->
<HTML>
<HEAD>
<!-- Generated by javadoc (build 1.6.0_21) on Sun May 05 22:11:00 EDT 2013 -->
<META http-equiv="Content-Type" content="text/html; charset=utf-8">
<TITLE>
${pkgName}
</TITLE>

<META NAME="date" CONTENT="${date}">

<LINK REL ="stylesheet" TYPE="text/css" HREF="${relatePath}stylesheet.css" TITLE="Style">

<SCRIPT type="text/javascript">
function windowTitle()
{
    if (location.href.indexOf('is-external=true') == -1) {
        parent.document.title="${pkgName}";
    }
}
</SCRIPT>
<NOSCRIPT>
</NOSCRIPT>

</HEAD>
<BODY BGCOLOR="white" onload="windowTitle();">

<H2>
${pkgName}
</H2>
Primary package containing general things.
<P>
<B>See:</B>
<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<A HREF="#package_description"><B>Description</B></A>
<P>

<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="2"><FONT SIZE="+2">
<B>Thing Summary</B></FONT></TH>
</TR>
<#list things as thing>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="15%"><B><A HREF="${relatePath}/${thing.getDocFilePath()}" title="thing ${thing.getCategoryName()}">${thing.getName()}</A></B></TD>
<TD>${thing.getSimpleDescription()}</TD>
</TR>
</#list>

<P>
<A NAME="package_description"><!-- --></A><H2>
Package ${pkgName} Description
</H2>

<P>
Primary package containing general things.
<P>

<P>
<DL>
</DL>
<HR>
</BODY>
</HTML>
